# Generated by Django 5.2.1 on 2025-06-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='editors_note',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='submission',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='submission',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='submission',
            name='author_bio',
            field=models.TextField(max_length=1000),
        ),
    ]
