# Generated by Django 5.2.1 on 2025-06-06 18:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_issue_editors_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='published_authors',
            field=models.ManyToManyField(related_name='published_issues', to=settings.AUTH_USER_MODEL),
        ),
    ]
