# Generated by Django 5.2.1 on 2025-06-06 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_issue_published_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('archived', 'Archived')], default='pending', max_length=9),
        ),
        migrations.AlterField(
            model_name='submission',
            name='approved_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='main_app.issue'),
        ),
    ]
