# Generated by Django 5.2.1 on 2025-06-06 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_issue_issue_status_alter_submission_approved_issue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='issue_status',
            new_name='status',
        ),
    ]
